site_name: My Demo mkdocs project
site_url: https://Stas-Nizhelskiy.github.io/mkdocs-demo1/
theme: 
  name: mkdocs
  site_author: Stanislav Nizhelskiy
  copyright: Stanislav Nizhelskiy, Demo, 2025
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
